INSERT INTO "Model_Alfa_Romeo" VALUES(1,5,'4C');
INSERT INTO "Model_Alfa_Romeo" VALUES(2,5,'8C');
INSERT INTO "Model_Alfa_Romeo" VALUES(3,5,'Alfa 145');
INSERT INTO "Model_Alfa_Romeo" VALUES(4,5,'Alfa 146');
INSERT INTO "Model_Alfa_Romeo" VALUES(5,5,'Alfa 147');
INSERT INTO "Model_Alfa_Romeo" VALUES(6,5,'Alfa 155');
INSERT INTO "Model_Alfa_Romeo" VALUES(7,5,'Alfa 156');
INSERT INTO "Model_Alfa_Romeo" VALUES(8,5,'Alfa 159');
INSERT INTO "Model_Alfa_Romeo" VALUES(9,5,'Alfa 164');
INSERT INTO "Model_Alfa_Romeo" VALUES(10,5,'Alfa 166');
INSERT INTO "Model_Alfa_Romeo" VALUES(11,5,'Alfa 33');
INSERT INTO "Model_Alfa_Romeo" VALUES(12,5,'Alfa 75');
INSERT INTO "Model_Alfa_Romeo" VALUES(13,5,'Alfa 90');
INSERT INTO "Model_Alfa_Romeo" VALUES(14,5,'Alfasud');
INSERT INTO "Model_Alfa_Romeo" VALUES(15,5,'Alfetta');
INSERT INTO "Model_Alfa_Romeo" VALUES(16,5,'Brera');
INSERT INTO "Model_Alfa_Romeo" VALUES(17,5,'Crosswagon');
INSERT INTO "Model_Alfa_Romeo" VALUES(18,5,'Giulia');
INSERT INTO "Model_Alfa_Romeo" VALUES(19,5,'Giulietta');
INSERT INTO "Model_Alfa_Romeo" VALUES(20,5,'GT');
INSERT INTO "Model_Alfa_Romeo" VALUES(21,5,'GTV');
INSERT INTO "Model_Alfa_Romeo" VALUES(22,5,'Junior');
INSERT INTO "Model_Alfa_Romeo" VALUES(23,5,'MiTo');
INSERT INTO "Model_Alfa_Romeo" VALUES(24,5,'Spider');
INSERT INTO "Model_Alfa_Romeo" VALUES(25,5,'Sprint');
INSERT INTO "Model_Alfa_Romeo" VALUES(26,5,'Stelvio');
